### PR TITLE
Removed meaningless key

### PR DESCRIPTION
**Pull request by GeekTrainer**
## Use this template to add a workshop to this repo. Add the following items:

- [ ] Your workshop design document, filled in with some details about your proposed workshop including its title and the three stages in the designer delineated, using the `workshop-designer.md` file in the template.

- [ ] A `README.md` file that describes the steps of the workshop. 

- [ ] Powerpoint Slides for the workshop.

- [ ] The workshop's solution in the `/solution` folder.

- [ ] An embedded Train the Trainer video.

- [ ] A Call to Action to enhance the workshop with a direct line to Microsoft Learn by linking to an appropriate Learn module.

- [ ] Code quality check: no authentication keys should be included in solution or sample code

A reviewer will be assigned to the workshop and will work with you to shape it for production. Thank you for your contribution!

### CODE REVIEW

**Comment by GeekTrainer** [comment]
This PR actually removes the key. It's not an actual security issue as it's a sample site and the key is used for the app. But just to make the system happy it's been removed with instructions on the README on how to generate one.

**Review by jlooper — APPROVED** [review]

**Comment by alfredodeza** [comment]
> This PR actually removes the key. It's not an actual security issue as it's a sample site and the key is used for the app. But just to make the system happy it's been removed with instructions on the README on how to generate one.

Since this PR also added an ignore entry for `__pycache__` I thought it was odd to leave the `pyc` files around. I'm happy to clean those up on a separate PR

**Comment by GeekTrainer** [comment]
I can go back and do that as well. Just an oversight on my part.

**Comment by alfredodeza** [comment]
@GeekTrainer no worries, addressed in PR #75

**Pull request merged**
