### PR TITLE
How to create canvas app workshop files

### PR DESCRIPTION
**Pull request by Haimantika**
Signed-off-by: Haimantika <haimantikamitra@gmail.com>

## Use this template to add a workshop to this repo. Add the following items:

- [x] Your workshop design document, filled in with some details about your proposed workshop including its title and the three stages in the designer delineated, using the `workshop-designer.md` file in the template.

- [x] A `README.md` file that describes the steps of the workshop. 

- [x] Powerpoint Slides for the workshop.

- [ ] The workshop's solution in the `/solution` folder.

- [ ] An embedded Train the Trainer video.

- [x] A Call to Action to enhance the workshop with a direct line to Microsoft Learn by linking to an appropriate Learn module.

A reviewer will be assigned to the workshop and will work with you to shape it for production. Thank you for your contribution!

### CODE REVIEW

**Review by jlooper — COMMENTED** [review]
hi! can you add a workshop designer doc? workshop-designer.md as per the template

**Comment by Haimantika** [comment]
> * workshop-designer.md

Oh yes sure, I missed it.

**Comment by jlooper** [comment]
awesome! thank you!

**Comment by Haimantika** [comment]
> awesome! thank you!

Done. Let me know if there is a need to squash the commits into one.

**Pull request merged**
